<a href="https://colab.research.google.com/github/bcandraas/DSI_Assignment/blob/main/Data_Analyst_Test_DSI_Bintang_Candra_Ayu_Srikandi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Analyst Test for DSI (Bintang Candra Ayu Srikandi)

PETUNJUK :

Ada 3 File dalam Folder :
> Data Jasa Medis Dokter
> Data Jasa Medis Perawat
> Data Jasa Medis BC

Dari Ketiga Data ini memberikan informasi PASIEN siapa2 saja yang mereka tangani dan Jumlah FEE (FEE RP) yang mereka peroleh setelah menangani Pasien Tersebut.

Baik Dari Data Tabel Jasa Medis Dokter, Jasa Medis Perawat ataupun Jasa Medis BC BISA SAJA ada 2 Jasa Medis ataupun 3 Jasa Medis yang SECARA BERSAMAAN mengerjakan TREATMENT YANG SAMA KEPADA PASIEN YANG SAMA (berdasarkan Nomor KD Pasien).

SOAL 1: Gabungkan ketiga Data (Tabel) ini menjadi 1 TABEL YANG BARU yang berisikan Kolom :

> NOMOR KD PASIEN
> NAMA PASIEN
> TANGGAL
> NAMA DOKTER
> NAMA PERAWAT
> NAMA BC
> NAMA PRODUK
> HARGA/UNIT
> QTY
> FEE DOKTER
> FEE PERAWAT
> FEE BC

Pastikan tidak ada Data Ganda

SOAL 2: REKAPITULASI dalam TABEL
> Tabel Dokter dengan Jumlah Total Omset dan Total Fee
> Tabel Perawat dengan Jumlah Total Omset dan Total Fee
> Tabel BC dengan Jumlah Total Omset dan Total Fee


SOAL 3: REKAPITULASI dalam TABEL :
> Semua Nama Treatment dengan Urutan Jumlah Terbanyak berdasarkan Jumlah Omsetnya

HASIL YANG AKAN DIHARAPKAN :

1. SOAL 1 = 1 TABEL TOTAL REKAPITULASI PENJUALAN
2. SOAL 2 = 3 TABEL (TABEL DOKTER, TABEL PERAWAT, TABEL BC)
3. SOAL 3 = 1 TABEL REKAPITLASI TREATMENT

## Soal 1
1 TABEL TOTAL REKAPITULASI PENJUALAN

In [161]:
import pandas as pd

# Load files
dokter = pd.read_excel("Data Jasa Medis Detail - Dokter (2022-08 Agustus 1-31).xlsx")
perawat = pd.read_excel("Data Jasa Medis Detail - Perawat (2022-08 Agustus 1-31).xlsx")
bc = pd.read_excel("Data Jasa Medis Detail - BC (2022-08 Agustus 1-31).xlsx")

In [162]:
# Check table Dokter
print("Dokter:", dokter.columns)

Dokter: Index(['NO TRANSAKSI', 'KD PASIEN', 'NAMA PASIEN', 'TANGGAL', 'NAMA DOKTER',
       'NAMA PRODUK', 'HARGA/UNIT', 'QTY', 'TOTAL', 'FEE MEDIS DOKTER',
       'JUMLAH MEDIS', 'FEE RP DOKTER'],
      dtype='object')

In [163]:
# Check table Perawat
print("Perawat:", perawat.columns)

Perawat: Index(['NO TRANSAKSI', 'KD PASIEN', 'NAMA PASIEN', 'TANGGAL', 'NAMA PERAWAT',
       'NAMA PRODUK', 'HARGA/UNIT', 'QTY', 'TOTAL', 'FEE PERAWAT',
       'JUMLAH MEDIS', 'FEE RP PERAWAT'],
      dtype='object')

In [164]:
#Check table BC
print("BC:", bc.columns)

BC: Index(['NO TRANSAKSI', 'KD PASIEN', 'NAMA PASIEN', 'TANGGAL', 'NAMA BC',
       'NAMA PRODUK', 'HARGA/UNIT', 'QTY', 'TOTAL', 'FEE BC', 'JUMLAH MEDIS',
       'FEE RP BC'],
      dtype='object')

In [165]:
# Merge Dokter - Perawat into new table
df_merge = pd.merge(dokter, perawat,
                    on=['KD PASIEN','NAMA PASIEN','TANGGAL','NAMA PRODUK','HARGA/UNIT','QTY'],
                    how='outer')

# Merge new table - BC
df_merge = pd.merge(df_merge, bc,
                    on=['KD PASIEN','NAMA PASIEN','TANGGAL','NAMA PRODUK','HARGA/UNIT','QTY'],
                    how='outer')

df_merge

,NO TRANSAKSI_x,KD PASIEN,NAMA PASIEN,TANGGAL,NAMA DOKTER,NAMA PRODUK,HARGA/UNIT,QTY,TOTAL_x,FEE MEDIS DOKTER,...,TOTAL_y,FEE PERAWAT,JUMLAH MEDIS_y,FEE RP PERAWAT,NO TRANSAKSI,NAMA BC,TOTAL,FEE BC,JUMLAH MEDIS,FEE RP BC
0,NaN,1001779,diah mitasari,2022-08-08,NaN,Jet Peel Whitening,25000,1,NaN,NaN,...,NaN,NaN,NaN,NaN,003220808-028,Ruwaida,96255.0,7.0,1.0,6738.0
1,NaN,1012769,FRANSISKA DWI LESTARI,2022-08-29,NaN,Platinum Jerawat Therapy,70000,1,NaN,NaN,...,NaN,NaN,NaN,NaN,003220829-049,Yuni,269514.0,3.0,1.0,8086.0
2,003220810-008,1013254,citrA,2022-08-10,dr. Kangen,Platinum Acne Therapy,70000,1,289800.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,1013254,citrA,2022-08-10,NaN,Platinum Jerawat Therapy,70000,1,NaN,NaN,...,NaN,NaN,NaN,NaN,003220810-008,Hani,289800.0,3.0,1.0,8694.0
4,NaN,1013695,afrina zahra b,2022-08-28,NaN,Paket Severe Jerawat Treatment,20000,1,NaN,NaN,...,NaN,NaN,NaN,NaN,003220828-026,Hani,810000.0,2.0,1.0,16200.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1077,NaN,3002843,DAMILAH,2022-08-31,NaN,Paket Infus baby luxury,150000,1,NaN,NaN,...,1129950.0,3.0,1.0,33899.0,NaN,NaN,NaN,NaN,NaN,NaN
1078,NaN,3002846,NOVA ARYANI,2022-08-31,NaN,Jerawat Boxer Injeksi,9000,1,NaN,NaN,...,8100.0,5.0,1.0,4050.0,NaN,NaN,NaN,NaN,NaN,NaN
1079,NaN,3002849,MUHAMMAD HAFID A.R,2022-08-31,NaN,Paket Jerawat Glow Boxer,125000,1,NaN,NaN,...,433148.0,0.6,1.0,2599.0,NaN,NaN,NaN,NaN,NaN,NaN
1080,NaN,3002852,MUHAMMAD ALDO P,2022-08-31,NaN,Diamond Hair Growth Treatment,110000,1,NaN,NaN,...,423522.0,0.7,1.0,2965.0,NaN,NaN,NaN,NaN,NaN,NaN
1081,NaN,3002918,DENA NINGTYAS SAPUTRI,2022-08-23,NaN,Paket Injeksi lemak,166666,2,NaN,NaN,...,333332.0,2.0,1.0,6667.0,NaN,NaN,NaN,NaN,NaN,NaN

In [166]:
# Remove Duplicates
df_merge = df_merge.drop_duplicates()
df_merge.duplicated().sum()

np.int64(0)

In [167]:
# Select the columns to be used
df_merge = df_merge[['KD PASIEN','NAMA PASIEN','TANGGAL','NAMA DOKTER','NAMA PERAWAT',
                     'NAMA BC','NAMA PRODUK','HARGA/UNIT','QTY',
                     'FEE RP DOKTER','FEE RP PERAWAT','FEE RP BC']]

df_merge

,KD PASIEN,NAMA PASIEN,TANGGAL,NAMA DOKTER,NAMA PERAWAT,NAMA BC,NAMA PRODUK,HARGA/UNIT,QTY,FEE RP DOKTER,FEE RP PERAWAT,FEE RP BC
0,1001779,diah mitasari,2022-08-08,NaN,NaN,Ruwaida,Jet Peel Whitening,25000,1,NaN,NaN,6738.0
1,1012769,FRANSISKA DWI LESTARI,2022-08-29,NaN,NaN,Yuni,Platinum Jerawat Therapy,70000,1,NaN,NaN,8086.0
2,1013254,citrA,2022-08-10,dr. Kangen,NaN,NaN,Platinum Acne Therapy,70000,1,17388.0,NaN,NaN
3,1013254,citrA,2022-08-10,NaN,NaN,Hani,Platinum Jerawat Therapy,70000,1,NaN,NaN,8694.0
4,1013695,afrina zahra b,2022-08-28,NaN,NaN,Hani,Paket Severe Jerawat Treatment,20000,1,NaN,NaN,16200.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1077,3002843,DAMILAH,2022-08-31,NaN,Riyu,NaN,Paket Infus baby luxury,150000,1,NaN,33899.0,NaN
1078,3002846,NOVA ARYANI,2022-08-31,NaN,dr. Kangen,NaN,Jerawat Boxer Injeksi,9000,1,NaN,4050.0,NaN
1079,3002849,MUHAMMAD HAFID A.R,2022-08-31,NaN,Suhi,NaN,Paket Jerawat Glow Boxer,125000,1,NaN,2599.0,NaN
1080,3002852,MUHAMMAD ALDO P,2022-08-31,NaN,Cinuk,NaN,Diamond Hair Growth Treatment,110000,1,NaN,2965.0,NaN
1081,3002918,DENA NINGTYAS SAPUTRI,2022-08-23,NaN,Wati,NaN,Paket Injeksi lemak,166666,2,NaN,6667.0,NaN

In [168]:
# Check missing value (NaN)
df_merge.isna().sum()

KD PASIEN           0
NAMA PASIEN         0
TANGGAL             0
NAMA DOKTER       725
NAMA PERAWAT      779
NAMA BC           372
NAMA PRODUK         0
HARGA/UNIT          0
QTY                 0
FEE RP DOKTER     725
FEE RP PERAWAT    779
FEE RP BC         372
dtype: int64

In [169]:
# Change NaN to 0 in FEE DOKTER, PERAWAT and BC
df_merge['FEE RP DOKTER'] = df_merge['FEE RP DOKTER'].fillna(0)
df_merge['FEE RP PERAWAT'] = df_merge['FEE RP PERAWAT'].fillna(0)
df_merge['FEE RP BC'] = df_merge['FEE RP BC'].fillna(0)

df_merge

,KD PASIEN,NAMA PASIEN,TANGGAL,NAMA DOKTER,NAMA PERAWAT,NAMA BC,NAMA PRODUK,HARGA/UNIT,QTY,FEE RP DOKTER,FEE RP PERAWAT,FEE RP BC
0,1001779,diah mitasari,2022-08-08,NaN,NaN,Ruwaida,Jet Peel Whitening,25000,1,0.0,0.0,6738.0
1,1012769,FRANSISKA DWI LESTARI,2022-08-29,NaN,NaN,Yuni,Platinum Jerawat Therapy,70000,1,0.0,0.0,8086.0
2,1013254,citrA,2022-08-10,dr. Kangen,NaN,NaN,Platinum Acne Therapy,70000,1,17388.0,0.0,0.0
3,1013254,citrA,2022-08-10,NaN,NaN,Hani,Platinum Jerawat Therapy,70000,1,0.0,0.0,8694.0
4,1013695,afrina zahra b,2022-08-28,NaN,NaN,Hani,Paket Severe Jerawat Treatment,20000,1,0.0,0.0,16200.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1077,3002843,DAMILAH,2022-08-31,NaN,Riyu,NaN,Paket Infus baby luxury,150000,1,0.0,33899.0,0.0
1078,3002846,NOVA ARYANI,2022-08-31,NaN,dr. Kangen,NaN,Jerawat Boxer Injeksi,9000,1,0.0,4050.0,0.0
1079,3002849,MUHAMMAD HAFID A.R,2022-08-31,NaN,Suhi,NaN,Paket Jerawat Glow Boxer,125000,1,0.0,2599.0,0.0
1080,3002852,MUHAMMAD ALDO P,2022-08-31,NaN,Cinuk,NaN,Diamond Hair Growth Treatment,110000,1,0.0,2965.0,0.0
1081,3002918,DENA NINGTYAS SAPUTRI,2022-08-23,NaN,Wati,NaN,Paket Injeksi lemak,166666,2,0.0,6667.0,0.0

In [170]:
# Check missing value (NaN) for FEE RP DOKTER, PERAWAT and BC
df_merge.isna().sum()

KD PASIEN           0
NAMA PASIEN         0
TANGGAL             0
NAMA DOKTER       725
NAMA PERAWAT      779
NAMA BC           372
NAMA PRODUK         0
HARGA/UNIT          0
QTY                 0
FEE RP DOKTER       0
FEE RP PERAWAT      0
FEE RP BC           0
dtype: int64

In [171]:
# Rename columns name
df_merge = df_merge.rename(columns={
    "FEE RP DOKTER": "FEE DOKTER",
    "FEE RP PERAWAT": "FEE PERAWAT",
    "FEE RP BC": "FEE BC",})

df_merge

,KD PASIEN,NAMA PASIEN,TANGGAL,NAMA DOKTER,NAMA PERAWAT,NAMA BC,NAMA PRODUK,HARGA/UNIT,QTY,FEE DOKTER,FEE PERAWAT,FEE BC
0,1001779,diah mitasari,2022-08-08,NaN,NaN,Ruwaida,Jet Peel Whitening,25000,1,0.0,0.0,6738.0
1,1012769,FRANSISKA DWI LESTARI,2022-08-29,NaN,NaN,Yuni,Platinum Jerawat Therapy,70000,1,0.0,0.0,8086.0
2,1013254,citrA,2022-08-10,dr. Kangen,NaN,NaN,Platinum Acne Therapy,70000,1,17388.0,0.0,0.0
3,1013254,citrA,2022-08-10,NaN,NaN,Hani,Platinum Jerawat Therapy,70000,1,0.0,0.0,8694.0
4,1013695,afrina zahra b,2022-08-28,NaN,NaN,Hani,Paket Severe Jerawat Treatment,20000,1,0.0,0.0,16200.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1077,3002843,DAMILAH,2022-08-31,NaN,Riyu,NaN,Paket Infus baby luxury,150000,1,0.0,33899.0,0.0
1078,3002846,NOVA ARYANI,2022-08-31,NaN,dr. Kangen,NaN,Jerawat Boxer Injeksi,9000,1,0.0,4050.0,0.0
1079,3002849,MUHAMMAD HAFID A.R,2022-08-31,NaN,Suhi,NaN,Paket Jerawat Glow Boxer,125000,1,0.0,2599.0,0.0
1080,3002852,MUHAMMAD ALDO P,2022-08-31,NaN,Cinuk,NaN,Diamond Hair Growth Treatment,110000,1,0.0,2965.0,0.0
1081,3002918,DENA NINGTYAS SAPUTRI,2022-08-23,NaN,Wati,NaN,Paket Injeksi lemak,166666,2,0.0,6667.0,0.0

In [172]:
# Export to excel file
df_merge.to_excel("Rekap_Soal1.xlsx", index=False)

## Soal 2
3 TABEL (TABEL DOKTER, TABEL PERAWAT, TABEL BC)

In [173]:
import pandas as pd

# Load files
dokter = pd.read_excel("Data Jasa Medis Detail - Dokter (2022-08 Agustus 1-31).xlsx")
perawat = pd.read_excel("Data Jasa Medis Detail - Perawat (2022-08 Agustus 1-31).xlsx")
bc = pd.read_excel("Data Jasa Medis Detail - BC (2022-08 Agustus 1-31).xlsx")

In [174]:
# Check Missing Value
dokter.isna().sum()

NO TRANSAKSI        0
KD PASIEN           0
NAMA PASIEN         0
TANGGAL             0
NAMA DOKTER         0
NAMA PRODUK         0
HARGA/UNIT          0
QTY                 0
TOTAL               0
FEE MEDIS DOKTER    0
JUMLAH MEDIS        0
FEE RP DOKTER       0
dtype: int64

In [175]:
# Check Missing Value
perawat.isna().sum()

NO TRANSAKSI      0
KD PASIEN         0
NAMA PASIEN       0
TANGGAL           0
NAMA PERAWAT      0
NAMA PRODUK       0
HARGA/UNIT        0
QTY               0
TOTAL             0
FEE PERAWAT       0
JUMLAH MEDIS      0
FEE RP PERAWAT    0
dtype: int64

In [176]:
# Check Missing Value
bc.isna().sum()

NO TRANSAKSI    0
KD PASIEN       0
NAMA PASIEN     0
TANGGAL         0
NAMA BC         0
NAMA PRODUK     0
HARGA/UNIT      0
QTY             0
TOTAL           0
FEE BC          0
JUMLAH MEDIS    0
FEE RP BC       0
dtype: int64

In [177]:
# Count total Group By Nama Dokter
df_dokter = dokter.groupby("NAMA DOKTER").agg(
    Total_Omset=("TOTAL", "sum"),
    Total_Fee=("FEE RP DOKTER", "sum")
).reset_index()

# Export to excel file
df_dokter.to_excel("RekapDokter_Soal2.xlsx", index=False)

df_dokter

  NAMA DOKTER  Total_Omset  Total_Fee
0   dr. Cinta      3266138     195969
1  dr. Kangen    122928295    7291691
2   dr. Rindu     91798479    5447748

In [178]:
# Count total Group By Nama Perawat
df_perawat = perawat.groupby("NAMA PERAWAT").agg(
    Total_Omset=("TOTAL", "sum"),
    Total_Fee=("FEE RP PERAWAT", "sum")
).reset_index()

# Export to excel file
df_perawat.to_excel("RekapPerawat_Soal2.xlsx", index=False)

df_perawat

  NAMA PERAWAT  Total_Omset  Total_Fee
0        Cinuk     23437256     638762
1         Lani     24794788     753589
2         Riyu     18307059     510856
3        Salma     14170823     565662
4         Suhi     18823993     492884
5         Wati     25649622     995106
6    dr. Cinta       147330      49217
7   dr. Kangen        16200       8100
8    dr. Rindu       584577      36039

In [179]:
# Count total Group By Nama BC
df_bc = bc.groupby("NAMA BC").agg(
    Total_Omset=("TOTAL", "sum"),
    Total_Fee=("FEE RP BC", "sum")
).reset_index()

# Export to excel file
df_bc.to_excel("RekapBC_Soal2.xlsx", index=False)

df_bc

    NAMA BC  Total_Omset  Total_Fee
0      Adel     14059778     338982
1     Cinuk     34071499     794804
2      Hani     33809948     783496
3      Lani     62482640    1382811
4     Reyna       480000       9600
5    Riyuni     33374365     719770
6    Rochin      6878052     157274
7   Ruwaida     46288426    1000943
8     Salma     46757001    1011983
9      Sela     33840791     739881
10     Wati     38008797     883875
11     Yani     11830098     250029
12     Yuni     13690246     298603

## Soal 3
1 TABEL REKAPITLASI TREATMENT

Tabel yang digunakan adalah tabel yang sudah dibuat di Soal 1

In [180]:
# Show table from Soal 1
df_merge

,KD PASIEN,NAMA PASIEN,TANGGAL,NAMA DOKTER,NAMA PERAWAT,NAMA BC,NAMA PRODUK,HARGA/UNIT,QTY,FEE DOKTER,FEE PERAWAT,FEE BC
0,1001779,diah mitasari,2022-08-08,NaN,NaN,Ruwaida,Jet Peel Whitening,25000,1,0.0,0.0,6738.0
1,1012769,FRANSISKA DWI LESTARI,2022-08-29,NaN,NaN,Yuni,Platinum Jerawat Therapy,70000,1,0.0,0.0,8086.0
2,1013254,citrA,2022-08-10,dr. Kangen,NaN,NaN,Platinum Acne Therapy,70000,1,17388.0,0.0,0.0
3,1013254,citrA,2022-08-10,NaN,NaN,Hani,Platinum Jerawat Therapy,70000,1,0.0,0.0,8694.0
4,1013695,afrina zahra b,2022-08-28,NaN,NaN,Hani,Paket Severe Jerawat Treatment,20000,1,0.0,0.0,16200.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1077,3002843,DAMILAH,2022-08-31,NaN,Riyu,NaN,Paket Infus baby luxury,150000,1,0.0,33899.0,0.0
1078,3002846,NOVA ARYANI,2022-08-31,NaN,dr. Kangen,NaN,Jerawat Boxer Injeksi,9000,1,0.0,4050.0,0.0
1079,3002849,MUHAMMAD HAFID A.R,2022-08-31,NaN,Suhi,NaN,Paket Jerawat Glow Boxer,125000,1,0.0,2599.0,0.0
1080,3002852,MUHAMMAD ALDO P,2022-08-31,NaN,Cinuk,NaN,Diamond Hair Growth Treatment,110000,1,0.0,2965.0,0.0
1081,3002918,DENA NINGTYAS SAPUTRI,2022-08-23,NaN,Wati,NaN,Paket Injeksi lemak,166666,2,0.0,6667.0,0.0

In [181]:
# Create new table Group By Nama Produk
df_treatment = df_merge.groupby("NAMA PRODUK").agg({
    "QTY": "sum",
    "HARGA/UNIT": "first",
    "FEE DOKTER": "sum",
    "FEE PERAWAT": "sum",
    "FEE BC": "sum"
}).reset_index()

df_treatment

,NAMA PRODUK,QTY,HARGA/UNIT,FEE DOKTER,FEE PERAWAT,FEE BC
0,2 in 1 Flek Therapy,1,10000,0.0,1802.0,5148.0
1,Acne Back Treatment,1,130000,16322.0,0.0,0.0
2,Acne Clear,1,45000,11300.0,0.0,0.0
3,Acne Glow Booster,2,125000,65138.0,0.0,0.0
4,Acne Oily Booster,1,10000,21344.0,0.0,0.0
...,...,...,...,...,...,...
217,Whitening Jerawat Repaire,9,30000,57753.0,0.0,184325.0
218,Whitening Mesoskin,2,360000,0.0,0.0,55444.0
219,Whitening Pico Cell,3,150000,74734.0,0.0,25950.0
220,Whitening Toning Booster,2,110000,50099.0,0.0,0.0
221,Whitening Toning Boxer,1,110000,0.0,0.0,7911.0

In [182]:
# Count Total Omset
df_treatment["TOTAL OMSET"] = df_treatment["QTY"] * df_treatment["HARGA/UNIT"]

df_treatment

,NAMA PRODUK,QTY,HARGA/UNIT,FEE DOKTER,FEE PERAWAT,FEE BC,TOTAL OMSET
0,2 in 1 Flek Therapy,1,10000,0.0,1802.0,5148.0,10000
1,Acne Back Treatment,1,130000,16322.0,0.0,0.0,130000
2,Acne Clear,1,45000,11300.0,0.0,0.0,45000
3,Acne Glow Booster,2,125000,65138.0,0.0,0.0,250000
4,Acne Oily Booster,1,10000,21344.0,0.0,0.0,10000
...,...,...,...,...,...,...,...
217,Whitening Jerawat Repaire,9,30000,57753.0,0.0,184325.0,270000
218,Whitening Mesoskin,2,360000,0.0,0.0,55444.0,720000
219,Whitening Pico Cell,3,150000,74734.0,0.0,25950.0,450000
220,Whitening Toning Booster,2,110000,50099.0,0.0,0.0,220000
221,Whitening Toning Boxer,1,110000,0.0,0.0,7911.0,110000

In [183]:
# Sort from the biggest turnover value
df_treatment = df_treatment.sort_values(by="TOTAL OMSET", ascending=False)

df_treatment

,NAMA PRODUK,QTY,HARGA/UNIT,FEE DOKTER,FEE PERAWAT,FEE BC,TOTAL OMSET
36,Fractional Jerawat Boxer,28,250000,496206.0,0.0,527105.0,7000000
120,Paket Lip Rejuve Laser,34,133333,114768.0,0.0,77640.0,4533322
111,Paket Injeksi lemak,28,158333,0.0,80428.0,0.0,4433324
143,Paket Profilo Glow,5,750000,827741.0,0.0,275915.0,3750000
214,Whitening Boxer Infus,24,120000,0.0,229405.0,0.0,2880000
...,...,...,...,...,...,...,...
142,Paket Premium Vampire Whitening,1,10000,19662.0,2294.0,6554.0,10000
157,Paket Totok wajah,1,8000,0.0,0.0,1854.0,8000
140,Paket Premium Stretchmark Treatment,3,2000,39969.0,9277.0,26505.0,6000
184,Premium Stretchmark Treatment,3,2000,87886.0,10254.0,14648.0,6000
19,Derma Repair Cell,3,1000,23102.0,8351.0,7701.0,3000

In [184]:
# Export to excel file
df_treatment.to_excel("RekapTreatment_Soal3.xlsx", index=False)